#!/usr/bin/env python3
"""
generate_uuids.py — one-shot BLE UUID generator for the Narbis earclip protocol.

Run this once at protocol inception. Paste the C block into narbis_protocol.h
and the TS block into uuids.ts. Re-running regenerates fresh UUIDs and breaks
every paired device — only do that on a deliberate protocol-version bump.
"""

import sys
import uuid


CHARACTERISTICS = [
    ("NARBIS_SVC",              "Custom Narbis service (primary)"),
    ("NARBIS_CHR_IBI",          "IBI notify (per-beat or batched, depending on ble_profile)"),
    ("NARBIS_CHR_SQI",          "SQI notify (signal quality indicator)"),
    ("NARBIS_CHR_RAW_PPG",      "Raw PPG notify (gated on data_format)"),
    ("NARBIS_CHR_BATTERY",      "Custom battery notify (richer than standard 0x180F)"),
    ("NARBIS_CHR_CONFIG",       "Current runtime config — read + notify"),
    ("NARBIS_CHR_CONFIG_WRITE", "Config write (whole struct or single field)"),
    ("NARBIS_CHR_MODE",         "Mode write (3-axis: transport / ble_profile / data_format)"),
    ("NARBIS_CHR_OTA_CONTROL",  "OTA control (Nordic-style DFU; payload format owned by Stage 08)"),
    ("NARBIS_CHR_DIAGNOSTICS",  "Diagnostics notify (free heap, uptime, RSSI, etc.)"),
]


def uuid_to_c_bytes(u: uuid.UUID) -> str:
    """Return BLE-order (pure little-endian) byte-array literal for
    esp_bt_uuid_t / ble_uuid128_t.value.

    Do NOT use uuid.UUID.bytes_le here — that returns Microsoft GUID
    layout (time_low/mid/hi_version little-endian, the rest big-endian),
    which is NOT what BLE expects on the wire. NimBLE/ESP-IDF write
    .value byte-for-byte to the air interface, LSB first, so we want
    the UUID's full 16 bytes reversed end-to-end."""
    return "{ " + ", ".join(f"0x{b:02X}" for b in u.bytes[::-1]) + " }"


def main() -> int:
    pairs = [(name, desc, uuid.uuid4()) for name, desc in CHARACTERISTICS]

    print("// =============================================================")
    print("// Generated by protocol/generate_uuids.py")
    print("// Paste this block into protocol/narbis_protocol.h")
    print("// =============================================================\n")
    for name, desc, u in pairs:
        print(f"// {desc}")
        print(f'#define {name}_UUID_STR    "{str(u)}"')
        print(f"#define {name}_UUID_BYTES  {uuid_to_c_bytes(u)}")
        print()

    print("// =============================================================")
    print("// Paste this block into protocol/uuids.ts")
    print("// (these MUST be the same UUIDs as the C block above)")
    print("// =============================================================\n")
    for name, desc, u in pairs:
        print(f"// {desc}")
        print(f'export const {name}_UUID = "{str(u)}";')
    print()

    print("// Reminder: re-running this script regenerates ALL UUIDs.")
    print("// Only do that on a deliberate protocol-version bump.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
