/*
 * narbis_protocol.h — shared protocol definitions for the Narbis earclip.
 *
 * This file is the SINGLE SOURCE OF TRUTH for:
 *   - ESP-NOW packet layout (wire format) between the earclip and Edge glasses.
 *   - BLE service / characteristic UUIDs exposed by the earclip.
 *   - The runtime-tweakable configuration struct.
 *   - Internal types shared across firmware components (e.g. beat_event_t).
 *
 * Conventions (DO NOT VIOLATE — see CLAUDE.md):
 *   - All multi-byte integers are little-endian on the wire.
 *   - All wire structs use __attribute__((packed)).
 *   - No `bool` (use uint8_t with 0/1).
 *   - No bit fields anywhere — use bitmask macros over uint8_t / uint16_t.
 *   - No floating point in wire formats — use fixed-point ints (e.g. _x10, _x100).
 *   - No encryption/signing fields (deferred to v2).
 *   - The TypeScript mirror is protocol/narbis_protocol.ts; protocol/check_sync.py
 *     verifies the two stay in sync.
 */

#ifndef NARBIS_PROTOCOL_H
#define NARBIS_PROTOCOL_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* =============================================================
 * Protocol version
 * ============================================================= */

#define NARBIS_PROTOCOL_VERSION 1

/* =============================================================
 * BLE UUIDs (generated by protocol/generate_uuids.py)
 *
 * The _STR form is used by ble_gatts setup paths that take strings.
 * The _BYTES form is the little-endian byte order required by ESP-IDF's
 * esp_bt_uuid_t / ble_uuid128_t fields.
 *
 * Standard SIG services (used as-is, no custom UUIDs):
 *   0x180D  Heart Rate Service
 *   0x180F  Battery Service
 *   0x180A  Device Information Service
 * ============================================================= */

/* Custom Narbis service (primary) */
#define NARBIS_SVC_UUID_STR    "a24080b2-8857-4785-b3ba-a43b66af4f28"
#define NARBIS_SVC_UUID_BYTES  { 0xB2, 0x80, 0x40, 0xA2, 0x57, 0x88, 0x85, 0x47, 0xB3, 0xBA, 0xA4, 0x3B, 0x66, 0xAF, 0x4F, 0x28 }

/* IBI notify (per-beat or batched, depending on ble_profile) */
#define NARBIS_CHR_IBI_UUID_STR    "78ef492f-66be-438d-a91e-ddfdb441b7bb"
#define NARBIS_CHR_IBI_UUID_BYTES  { 0x2F, 0x49, 0xEF, 0x78, 0xBE, 0x66, 0x8D, 0x43, 0xA9, 0x1E, 0xDD, 0xFD, 0xB4, 0x41, 0xB7, 0xBB }

/* SQI notify (signal quality indicator) */
#define NARBIS_CHR_SQI_UUID_STR    "2b614c61-bcdf-4a3f-a7e8-3b5a860c0347"
#define NARBIS_CHR_SQI_UUID_BYTES  { 0x61, 0x4C, 0x61, 0x2B, 0xDF, 0xBC, 0x3F, 0x4A, 0xA7, 0xE8, 0x3B, 0x5A, 0x86, 0x0C, 0x03, 0x47 }

/* Raw PPG notify (gated on data_format) */
#define NARBIS_CHR_RAW_PPG_UUID_STR    "6bacca91-7017-40fa-bb91-4ebf28a65a99"
#define NARBIS_CHR_RAW_PPG_UUID_BYTES  { 0x91, 0xCA, 0xAC, 0x6B, 0x17, 0x70, 0xFA, 0x40, 0xBB, 0x91, 0x4E, 0xBF, 0x28, 0xA6, 0x5A, 0x99 }

/* Custom battery notify (richer than standard 0x180F) */
#define NARBIS_CHR_BATTERY_UUID_STR    "b59d3ba1-78d1-4260-93c2-7e9e02329777"
#define NARBIS_CHR_BATTERY_UUID_BYTES  { 0xA1, 0x3B, 0x9D, 0xB5, 0xD1, 0x78, 0x60, 0x42, 0x93, 0xC2, 0x7E, 0x9E, 0x02, 0x32, 0x97, 0x77 }

/* Current runtime config — read + notify */
#define NARBIS_CHR_CONFIG_UUID_STR    "553abc98-6406-4e37-b9fd-34df85b2b6c1"
#define NARBIS_CHR_CONFIG_UUID_BYTES  { 0x98, 0xBC, 0x3A, 0x55, 0x06, 0x64, 0x37, 0x4E, 0xB9, 0xFD, 0x34, 0xDF, 0x85, 0xB2, 0xB6, 0xC1 }

/* Config write (whole struct or single field) */
#define NARBIS_CHR_CONFIG_WRITE_UUID_STR    "129fbe56-cbd6-4f52-957b-d80834d6abf3"
#define NARBIS_CHR_CONFIG_WRITE_UUID_BYTES  { 0x56, 0xBE, 0x9F, 0x12, 0xD6, 0xCB, 0x52, 0x4F, 0x95, 0x7B, 0xD8, 0x08, 0x34, 0xD6, 0xAB, 0xF3 }

/* Mode write (3-axis: transport / ble_profile / data_format) */
#define NARBIS_CHR_MODE_UUID_STR    "71db6de8-5bff-480f-8db1-0d01c90d17d0"
#define NARBIS_CHR_MODE_UUID_BYTES  { 0xE8, 0x6D, 0xDB, 0x71, 0xFF, 0x5B, 0x0F, 0x48, 0x8D, 0xB1, 0x0D, 0x01, 0xC9, 0x0D, 0x17, 0xD0 }

/* OTA control (Nordic-style DFU; payload format owned by Stage 08) */
#define NARBIS_CHR_OTA_CONTROL_UUID_STR    "a99ea74e-cc5b-469b-b6f8-333b3e7f9cdc"
#define NARBIS_CHR_OTA_CONTROL_UUID_BYTES  { 0x4E, 0xA7, 0x9E, 0xA9, 0x5B, 0xCC, 0x9B, 0x46, 0xB6, 0xF8, 0x33, 0x3B, 0x3E, 0x7F, 0x9C, 0xDC }

/* Diagnostics notify (free heap, uptime, RSSI, etc.) */
#define NARBIS_CHR_DIAGNOSTICS_UUID_STR    "31d99572-bf8a-4658-828e-4f7c138ca722"
#define NARBIS_CHR_DIAGNOSTICS_UUID_BYTES  { 0x72, 0x95, 0xD9, 0x31, 0x8A, 0xBF, 0x58, 0x46, 0x82, 0x8E, 0x4F, 0x7C, 0x13, 0x8C, 0xA7, 0x22 }

/* =============================================================
 * Enums
 * ============================================================= */

/* ESP-NOW message types. Values are stable on the wire — never renumber. */
typedef enum {
    NARBIS_MSG_IBI         = 0x01,  /* one or more beat events */
    NARBIS_MSG_RAW_PPG     = 0x02,  /* raw red+IR sample batch */
    NARBIS_MSG_BATTERY     = 0x03,  /* battery state */
    NARBIS_MSG_SQI         = 0x04,  /* signal quality indicator */
    NARBIS_MSG_HEARTBEAT   = 0x05,  /* keepalive + diagnostics summary */
    NARBIS_MSG_CONFIG_ACK  = 0x06   /* ack of a config write */
} narbis_msg_type_t;

/* Transport mode — earclip → Edge / dashboard routing. */
typedef enum {
    NARBIS_TRANSPORT_EDGE_ONLY = 0,
    NARBIS_TRANSPORT_HYBRID    = 1
} narbis_transport_mode_t;

/* BLE profile — controls notify cadence. */
typedef enum {
    NARBIS_BLE_BATCHED     = 0,  /* one notify every ble_batch_period_ms */
    NARBIS_BLE_LOW_LATENCY = 1   /* notify every beat */
} narbis_ble_profile_t;

/* Data format — what the dashboard wants to see. */
typedef enum {
    NARBIS_DATA_IBI_ONLY     = 0,
    NARBIS_DATA_RAW_PPG      = 1,
    NARBIS_DATA_IBI_PLUS_RAW = 2
} narbis_data_format_t;

/* Beat-event flag bitmask (union of zero or more bits). */
#define NARBIS_BEAT_FLAG_ARTIFACT       0x01u
#define NARBIS_BEAT_FLAG_LOW_SQI        0x02u
#define NARBIS_BEAT_FLAG_INTERPOLATED   0x04u
#define NARBIS_BEAT_FLAG_LOW_CONFIDENCE 0x08u

/* CONFIG_ACK status codes. */
typedef enum {
    NARBIS_CFG_ACK_OK               = 0,
    NARBIS_CFG_ACK_RANGE_ERROR      = 1,
    NARBIS_CFG_ACK_UNKNOWN_FIELD    = 2,
    NARBIS_CFG_ACK_REQUIRES_REBOOT  = 3
} narbis_config_ack_status_t;

/* =============================================================
 * Per-message payload structs (wire format)
 *
 * On the wire, only the active variant's bytes are emitted, preceded
 * by the packet header and followed by a 16-bit CRC. Payload size is
 * carried in the header's payload_len field.
 * ============================================================= */

/* Maximum samples per RAW_PPG packet, chosen so the full ESP-NOW frame
 * (header 12 + payload + crc 2) stays within the 250-byte ESP-NOW limit:
 *   header(12) + raw_ppg_header(4) + 29 * sample(8) + crc(2) = 250
 */
#define NARBIS_RAW_PPG_MAX_SAMPLES 29

/* IBI payload — a single inter-beat interval observation. */
typedef struct __attribute__((packed)) {
    uint16_t ibi_ms;            /* inter-beat interval, milliseconds (300–2000 typ.) */
    uint8_t  confidence_x100;   /* 0–100 → 0.00–1.00 confidence */
    uint8_t  flags;             /* NARBIS_BEAT_FLAG_* bitmask */
} narbis_ibi_payload_t;

/* RAW_PPG sample — one (red, IR) pair from the MAX3010x FIFO. */
typedef struct __attribute__((packed)) {
    uint32_t red;               /* raw ADC counts, channel red */
    uint32_t ir;                /* raw ADC counts, channel IR */
} narbis_raw_sample_t;

/* RAW_PPG payload — variable-length sample batch. n_samples ≤ NARBIS_RAW_PPG_MAX_SAMPLES. */
typedef struct __attribute__((packed)) {
    uint16_t sample_rate_hz;    /* sample rate at time of capture (Hz) */
    uint16_t n_samples;         /* number of valid entries in samples[] */
    narbis_raw_sample_t samples[NARBIS_RAW_PPG_MAX_SAMPLES];
} narbis_raw_ppg_payload_t;

/* BATTERY payload. */
typedef struct __attribute__((packed)) {
    uint16_t mv;                /* battery voltage in millivolts */
    uint8_t  soc_pct;           /* state of charge, 0–100 */
    uint8_t  charging;          /* 0 = not charging, 1 = charging */
} narbis_battery_payload_t;

/* SQI payload — signal quality indicator. */
typedef struct __attribute__((packed)) {
    uint16_t sqi_x100;             /* 0–100 → 0.00–1.00 signal quality */
    uint32_t dc_red;               /* DC level, red channel (ADC counts) */
    uint32_t dc_ir;                /* DC level, IR channel (ADC counts) */
    uint16_t perfusion_idx_x1000;  /* perfusion index × 1000 */
} narbis_sqi_payload_t;

/* HEARTBEAT payload — keepalive plus a small diagnostics digest.
 *
 * mode_byte packs the three mode enums for compactness:
 *   bits 0–1: transport_mode
 *   bits 2–3: ble_profile
 *   bits 4–5: data_format
 *   bits 6–7: reserved (must be 0)
 */
typedef struct __attribute__((packed)) {
    uint32_t uptime_s;          /* seconds since boot */
    uint32_t free_heap;         /* bytes of free heap on the earclip */
    int8_t   rssi_dbm;          /* last-seen ESP-NOW RSSI to peer */
    uint8_t  mode_byte;         /* packed mode enums (see above) */
    uint16_t reserved;          /* must be 0 */
} narbis_heartbeat_payload_t;

/* CONFIG_ACK payload — response to a config write. */
typedef struct __attribute__((packed)) {
    uint16_t config_version;    /* echo of config_version after write */
    uint8_t  status;            /* narbis_config_ack_status_t */
    uint8_t  field_id;          /* offset (in bytes) of the field, or 0xFF for whole-struct */
} narbis_config_ack_payload_t;

/* =============================================================
 * Packet header + in-memory packet
 *
 * Wire layout (variable length):
 *   [header 12 B][active payload (payload_len bytes)][crc16 2 B]
 *
 * The in-memory narbis_packet_t stores the full payload union for
 * ergonomic access; serialize/deserialize emit/consume only the active
 * variant's bytes based on header.msg_type.
 * ============================================================= */

typedef struct __attribute__((packed)) {
    uint8_t  msg_type;          /* narbis_msg_type_t */
    uint8_t  device_id;         /* per-earclip ID (0 = unset) */
    uint16_t seq_num;           /* per-(device,msg_type) monotonic counter */
    uint32_t timestamp_ms;      /* earclip-local milliseconds */
    uint16_t payload_len;       /* bytes of payload following this header */
    uint8_t  protocol_version;  /* must equal NARBIS_PROTOCOL_VERSION */
    uint8_t  reserved;          /* must be 0 */
} narbis_header_t;

#define NARBIS_HEADER_SIZE 12u
#define NARBIS_CRC_SIZE     2u
#define NARBIS_FRAME_OVERHEAD (NARBIS_HEADER_SIZE + NARBIS_CRC_SIZE)
#define NARBIS_MAX_FRAME_SIZE 250u  /* ESP-NOW payload cap */
#define NARBIS_MAX_PAYLOAD_SIZE (NARBIS_MAX_FRAME_SIZE - NARBIS_FRAME_OVERHEAD)

typedef union {
    narbis_ibi_payload_t        ibi;
    narbis_raw_ppg_payload_t    raw_ppg;
    narbis_battery_payload_t    battery;
    narbis_sqi_payload_t        sqi;
    narbis_heartbeat_payload_t  heartbeat;
    narbis_config_ack_payload_t config_ack;
} narbis_payload_t;

typedef struct {
    narbis_header_t  header;
    narbis_payload_t payload;
    uint16_t         crc16;     /* populated by serialize / verified by deserialize */
} narbis_packet_t;

/* =============================================================
 * Internal: beat_event_t
 *
 * Emitted by beat_validator, consumed by transport tasks. Carries more
 * context than the on-wire IBI payload (e.g. peak amplitude, sample
 * index for cross-referencing raw PPG). NEVER serialized to the wire.
 * ============================================================= */

typedef struct {
    uint32_t timestamp_ms;      /* earclip-local time at peak */
    uint16_t ibi_ms;            /* time since previous valid beat */
    uint16_t prev_ibi_ms;       /* IBI of the beat before this one (continuity check) */
    uint8_t  confidence_x100;   /* 0–100 */
    uint8_t  flags;             /* NARBIS_BEAT_FLAG_* */
    uint16_t peak_amplitude;    /* filtered-signal amplitude at the peak */
    uint32_t sample_index;      /* sample number from start of session */
} beat_event_t;

/* =============================================================
 * Runtime config
 *
 * Persisted to NVS, write-able via NARBIS_CHR_CONFIG_WRITE. Every field
 * is dashboard-tweakable. With the exception of sample_rate_hz, all
 * fields apply at runtime without a reboot.
 * ============================================================= */

typedef struct __attribute__((packed)) {
    /* ---- meta ---- */
    uint16_t config_version;        /* increments on incompatible NVS changes */

    /* ---- sensor ---- */
    uint16_t sample_rate_hz;        /* 50 / 100 / 200 / 400; reboot to apply */
    uint16_t led_red_ma_x10;        /* red LED current ×10 (default 70 = 7.0 mA) */
    uint16_t led_ir_ma_x10;         /* IR  LED current ×10 (default 70 = 7.0 mA) */

    /* ---- AGC ---- */
    uint8_t  agc_enabled;           /* 0/1 */
    uint8_t  reserved_agc;          /* pad to 16-bit boundary */
    uint16_t agc_update_period_ms;  /* how often AGC re-evaluates (default 200) */
    uint32_t agc_target_dc_min;     /* lower DC target (ADC counts) */
    uint32_t agc_target_dc_max;     /* upper DC target (ADC counts) */
    uint16_t agc_step_ma_x10;       /* per-update LED current step ×10 */

    /* ---- DSP ---- */
    uint16_t bandpass_low_hz_x100;  /* bandpass low cutoff ×100 (default 50 = 0.50 Hz) */
    uint16_t bandpass_high_hz_x100; /* bandpass high cutoff ×100 (default 800 = 8.00 Hz) */
    uint16_t elgendi_w1_ms;         /* Elgendi systolic peak window (ms, default 111) */
    uint16_t elgendi_w2_ms;         /* Elgendi beat window (ms, default 667) */
    uint16_t elgendi_beta_x1000;    /* Elgendi offset coefficient ×1000 (default 20 = 0.020) */

    /* ---- beat validator / SQI gating ---- */
    uint16_t sqi_threshold_x100;    /* min SQI to emit IBI (default 50 = 0.50) */
    uint16_t ibi_min_ms;            /* validator floor (default 300, ≈200 BPM) */
    uint16_t ibi_max_ms;            /* validator ceiling (default 2000, ≈30 BPM) */
    uint8_t  ibi_max_delta_pct;     /* continuity threshold (default 30) */

    /* ---- mode (3-axis) ---- */
    uint8_t  transport_mode;        /* narbis_transport_mode_t */
    uint8_t  ble_profile;           /* narbis_ble_profile_t */
    uint8_t  data_format;           /* narbis_data_format_t */

    /* ---- transport ---- */
    uint16_t ble_batch_period_ms;   /* BATCHED mode flush interval (default 500) */
    uint8_t  partner_mac[6];        /* ESP-NOW peer; all-zero = use Kconfig fallback */
    uint8_t  espnow_channel;        /* 1–13 */

    /* ---- power / diag ---- */
    uint8_t  diagnostics_enabled;   /* 0/1 */
    uint8_t  light_sleep_enabled;   /* 0/1 */
    uint8_t  reserved_pwr;          /* pad */
    uint16_t battery_low_mv;        /* below this, signal low-battery (default 3300) */
} narbis_runtime_config_t;

/* =============================================================
 * Helper API (impl in narbis_protocol.c)
 * ============================================================= */

/* CRC-16-CCITT-FALSE: poly 0x1021, init 0xFFFF, no reflect, no xor-out. */
uint16_t narbis_crc16_ccitt_false(const uint8_t *data, size_t len);

/* Returns the wire payload size for the given message type and packet,
 * or 0 if msg_type is unknown. RAW_PPG depends on n_samples. */
size_t narbis_payload_size(const narbis_packet_t *pkt);

/* Serialize pkt into buf. *out_len is set to the total bytes written
 * (header + payload + crc). Returns 0 on success, negative on error
 * (buf too small / unknown msg_type / payload too large). */
int narbis_packet_serialize(uint8_t *buf, size_t buf_len,
                            const narbis_packet_t *pkt, size_t *out_len);

/* Deserialize buf into pkt. Verifies CRC, protocol_version, and that
 * payload_len matches msg_type. Returns 0 on success, negative on error. */
int narbis_packet_deserialize(const uint8_t *buf, size_t buf_len,
                              narbis_packet_t *pkt);

/* Serialize / deserialize the runtime config. The wire form is just the
 * packed struct bytes followed by a CRC-16. */
int narbis_config_serialize(uint8_t *buf, size_t buf_len,
                            const narbis_runtime_config_t *cfg, size_t *out_len);
int narbis_config_deserialize(const uint8_t *buf, size_t buf_len,
                              narbis_runtime_config_t *cfg);

#define NARBIS_CONFIG_WIRE_SIZE (sizeof(narbis_runtime_config_t) + NARBIS_CRC_SIZE)

#ifdef __cplusplus
}
#endif

#endif /* NARBIS_PROTOCOL_H */
