export {
  NARBIS_SVC_UUID,
  NARBIS_CHR_IBI_UUID,
  NARBIS_CHR_SQI_UUID,
  NARBIS_CHR_RAW_PPG_UUID,
  NARBIS_CHR_BATTERY_UUID,
  NARBIS_CHR_CONFIG_UUID,
  NARBIS_CHR_CONFIG_WRITE_UUID,
  NARBIS_CHR_MODE_UUID,
  NARBIS_CHR_PEER_ROLE_UUID,
  NARBIS_CHR_DIAGNOSTICS_UUID,
  NARBIS_OTA_SVC_UUID16,
  NARBIS_OTA_CHR_CONTROL_UUID16,
  NARBIS_OTA_CHR_DATA_UUID16,
  NARBIS_OTA_CHR_STATUS_UUID16,
} from '../../../protocol/uuids';

export const HEART_RATE_SERVICE = 0x180d;
export const BATTERY_SERVICE = 0x180f;
export const DEVICE_INFO_SERVICE = 0x180a;
