import { HEART_RATE_SERVICE } from './characteristics';
import { parseHeartRateMeasurement } from './parsers';

export type PolarStatus = 'disconnected' | 'connecting' | 'connected' | 'reconnecting';

export interface PolarBeatEvent {
  bpm: number;
  rrIntervals_ms: number[];
  /* One monotonic timestamp per RR — generated by reconstructBeatTimestamps()
   * walking forward by RR sum from an anchor. Use these (NOT `timestamp`)
   * to plot or align beats. */
  beatTimestamps: number[];
  /** BLE notify receive time (Date.now()). Jitters relative to the actual
   * beat by BLE latency, so DO NOT use it as a beat time. */
  timestamp: number;
}

export interface PolarDisconnectedDetail {
  reason: 'user' | 'gatt' | 'error';
  error?: Error;
}

export interface PolarErrorDetail {
  error: Error;
  phase: string;
}

const HEART_RATE_MEASUREMENT_UUID = 0x2a37;
const RECONNECT_BACKOFF_MS = [1000, 2000, 4000, 8000, 16000, 30000];

/* Beat-clock thresholds. RESET re-anchors after a gap big enough that the
 * cumulative-RR clock is no longer trustworthy (strap removed, browser
 * tab backgrounded long enough to suppress notifications, etc.). DRIFT
 * snaps forward when Polar silently dropped beats and the RR sum has
 * fallen meaningfully behind wall-clock time. */
const BEAT_CLOCK_RESET_GAP_MS = 10_000;
const BEAT_CLOCK_DRIFT_LIMIT_MS = 2_000;

/* Polar beat clock — produces one monotonic timestamp per RR.
 *
 * The naïve "walk backwards from receive time by cumulative RR sum"
 * (formerly done in BeatChart, aggregator, and metrics/windowing) breaks
 * under BLE latency jitter: when notification N1 has higher latency than
 * N2, N2's first reconstructed beat can land BEFORE N1's last one, and
 * the live tachogram draws a backwards Z. This walks FORWARD from an
 * anchor, so beats are monotonic by construction.
 *
 * Re-anchor cases (caller responsibility — pass `prev = null` to trigger):
 *   - first notification ever
 *   - gap > RESET threshold since the last beat
 *   - disconnect / reconnect
 * On re-anchor we still place the LATEST beat at receiveTs and walk older
 * ones backwards — same offset the rest of the codebase used historically,
 * so the very first plotted points line up with wall time.
 *
 * Drift snap: if the cumulative RR sum has fallen meaningfully behind
 * wall-clock (Polar silently dropped notifications), uniformly shift this
 * notification's emitted timestamps forward so the latest beat lands at
 * receiveTs. Monotonicity is preserved because every RR is positive, so
 * the shifted first beat is still after the previous anchor.
 *
 * Pure — caller owns the anchor state. Used by PolarH10 live ingest AND
 * by the replay loader to regenerate beatTimestamps for pre-clock
 * recording bundles.
 */
export function walkPolarBeatClock(
  prev: number | null,
  receiveTs: number,
  rrs: number[],
): { beatTimestamps: number[]; next: number | null } {
  if (rrs.length === 0) return { beatTimestamps: [], next: prev };
  const reanchor = prev == null || receiveTs - prev > BEAT_CLOCK_RESET_GAP_MS;
  if (reanchor) {
    let total = 0;
    for (let i = 0; i < rrs.length; i++) total += rrs[i];
    let cursor = receiveTs - total;
    const out: number[] = new Array(rrs.length);
    for (let i = 0; i < rrs.length; i++) {
      cursor += rrs[i];
      out[i] = cursor;
    }
    return { beatTimestamps: out, next: out[out.length - 1] };
  }
  let cursor = prev as number;
  const out: number[] = new Array(rrs.length);
  for (let i = 0; i < rrs.length; i++) {
    cursor += rrs[i];
    out[i] = cursor;
  }
  const drift = receiveTs - cursor;
  if (drift > BEAT_CLOCK_DRIFT_LIMIT_MS) {
    for (let i = 0; i < out.length; i++) out[i] += drift;
    cursor += drift;
  }
  return { beatTimestamps: out, next: cursor };
}

interface ListenerHandle {
  target: BluetoothRemoteGATTCharacteristic;
  type: string;
  listener: (ev: Event) => void;
}

export class PolarH10 extends EventTarget {
  private device: BluetoothDevice | null = null;
  private server: BluetoothRemoteGATTServer | null = null;
  private listeners: ListenerHandle[] = [];
  private intentionalDisconnect = false;
  private _status: PolarStatus = 'disconnected';
  private _deviceName: string | null = null;
  /* Anchor for the per-beat clock — see reconstructBeatTimestamps(). Null
   * means "no beat seen yet"; the next notification will anchor. Cleared
   * on connect and on any disconnect (intentional or GATT-dropped). */
  private lastBeatTimestamp: number | null = null;

  get status(): PolarStatus {
    return this._status;
  }

  get deviceName(): string | null {
    return this._deviceName;
  }

  async connect(): Promise<void> {
    if (this._status === 'connecting' || this._status === 'connected') return;
    if (!navigator.bluetooth) {
      throw new Error('Web Bluetooth is not available in this browser');
    }
    this.intentionalDisconnect = false;
    this.lastBeatTimestamp = null;
    this.setStatus('connecting');
    try {
      const device = await navigator.bluetooth.requestDevice({
        filters: [{ services: [HEART_RATE_SERVICE] }, { namePrefix: 'Polar' }],
        optionalServices: [HEART_RATE_SERVICE],
      });
      this.device = device;
      this._deviceName = device.name ?? 'Polar H10';
      device.addEventListener('gattserverdisconnected', this.onGattDisconnected);
      await this.openSession();
      this.setStatus('connected');
      this.dispatch('connected', { name: this._deviceName });
    } catch (err) {
      this.setStatus('disconnected');
      this.cleanupConnection();
      throw err;
    }
  }

  async disconnect(): Promise<void> {
    this.intentionalDisconnect = true;
    if (this.device?.gatt?.connected) {
      this.device.gatt.disconnect();
    } else {
      this.setStatus('disconnected');
      this.cleanupConnection();
      this.dispatch('disconnected', { reason: 'user' } as PolarDisconnectedDetail);
      this.intentionalDisconnect = false;
    }
  }

  private async openSession(): Promise<void> {
    if (!this.device?.gatt) throw new Error('no GATT server');
    this.server = await this.device.gatt.connect();

    const hrSvc = await this.server.getPrimaryService(HEART_RATE_SERVICE);
    const hrCh = await hrSvc.getCharacteristic(HEART_RATE_MEASUREMENT_UUID);
    hrCh.addEventListener('characteristicvaluechanged', this.onHrNotify);
    this.listeners.push({ target: hrCh, type: 'characteristicvaluechanged', listener: this.onHrNotify });
    await hrCh.startNotifications();
  }

  private onGattDisconnected = (): void => {
    /* Drop the beat-clock anchor on every disconnect path — the strap may
     * have been moved, swapped, or held idle long enough that summing RRs
     * forward from the old anchor would no longer track wall-clock. */
    this.lastBeatTimestamp = null;
    if (this.intentionalDisconnect) {
      this.setStatus('disconnected');
      this.cleanupConnection();
      this.dispatch('disconnected', { reason: 'user' } as PolarDisconnectedDetail);
      this.intentionalDisconnect = false;
      return;
    }
    this.setStatus('reconnecting');
    this.cleanupConnection({ keepDevice: true });
    this.dispatch('disconnected', { reason: 'gatt' } as PolarDisconnectedDetail);
    void this.reconnectLoop();
  };

  private async reconnectLoop(): Promise<void> {
    let attempt = 0;
    while (!this.intentionalDisconnect && this.device) {
      const delay = RECONNECT_BACKOFF_MS[Math.min(attempt, RECONNECT_BACKOFF_MS.length - 1)];
      await sleep(delay);
      if (this.intentionalDisconnect || !this.device) return;
      try {
        await this.openSession();
        this.setStatus('connected');
        this.dispatch('connected', { name: this._deviceName ?? 'Polar H10' });
        return;
      } catch (err) {
        this.emitError(err, `reconnect-attempt-${attempt + 1}`);
        attempt += 1;
      }
    }
  }

  private onHrNotify = (ev: Event): void => {
    try {
      const dv = (ev.target as BluetoothRemoteGATTCharacteristic).value;
      if (!dv) return;
      const { bpm, rrIntervals_ms } = parseHeartRateMeasurement(dv);
      const receiveTs = Date.now();
      const beatTimestamps = this.reconstructBeatTimestamps(receiveTs, rrIntervals_ms);
      const detail: PolarBeatEvent = {
        bpm,
        rrIntervals_ms,
        beatTimestamps,
        timestamp: receiveTs,
      };
      this.dispatch('beatReceived', detail);
    } catch (err) {
      this.emitError(err, 'hr-parse');
    }
  };

  private reconstructBeatTimestamps(receiveTs: number, rrs: number[]): number[] {
    const { beatTimestamps, next } = walkPolarBeatClock(
      this.lastBeatTimestamp,
      receiveTs,
      rrs,
    );
    this.lastBeatTimestamp = next;
    return beatTimestamps;
  }

  private cleanupConnection(opts: { keepDevice?: boolean } = {}): void {
    for (const h of this.listeners) {
      h.target.removeEventListener(h.type, h.listener);
    }
    this.listeners = [];
    this.server = null;
    if (!opts.keepDevice) {
      if (this.device) {
        this.device.removeEventListener('gattserverdisconnected', this.onGattDisconnected);
      }
      this.device = null;
      this._deviceName = null;
    }
  }

  private setStatus(s: PolarStatus): void {
    this._status = s;
  }

  private dispatch<T>(type: string, detail: T): void {
    this.dispatchEvent(new CustomEvent<T>(type, { detail }));
  }

  private emitError(err: unknown, phase: string): void {
    const error = err instanceof Error ? err : new Error(String(err));
    this.dispatch('error', { error, phase } as PolarErrorDetail);
  }
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export const polarH10 = new PolarH10();
